INSERT INTO apartment (apartment_id, type, capacity, floor, description) VALUES
(1, 'ONE_BEDROOM', 2, 9, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(2, 'ONE_BEDROOM', 2, 1, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(3, 'ONE_BEDROOM', 2, 5, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(4, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(5, 'ONE_BEDROOM', 2, 1, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(6, 'ONE_BEDROOM', 2, 0, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(7, 'TWO_BEDROOM', 4, 5, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(8, 'ONE_BEDROOM', 2, 0, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(9, 'TWO_BEDROOM', 4, 10, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(10, 'TWO_BEDROOM', 4, 6, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(11, 'ONE_BEDROOM', 2, 9, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(12, 'TWO_BEDROOM', 4, 5, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(13, 'TWO_BEDROOM', 4, 5, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(14, 'ONE_BEDROOM', 2, 2, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(15, 'ONE_BEDROOM', 2, 1, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(16, 'TWO_BEDROOM', 4, 2, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(17, 'ONE_BEDROOM', 2, 7, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(18, 'TWO_BEDROOM', 4, 2, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(19, 'TWO_BEDROOM', 4, 4, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(20, 'TWO_BEDROOM', 4, 7, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(21, 'TWO_BEDROOM', 4, 8, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(22, 'TWO_BEDROOM', 4, 3, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(23, 'ONE_BEDROOM', 2, 9, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(24, 'ONE_BEDROOM', 2, 7, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(25, 'TWO_BEDROOM', 4, 4, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(26, 'TWO_BEDROOM', 4, 8, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(27, 'ONE_BEDROOM', 2, 10, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(28, 'ONE_BEDROOM', 2, 9, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(29, 'TWO_BEDROOM', 4, 8, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(30, 'ONE_BEDROOM', 2, 3, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(31, 'ONE_BEDROOM', 2, 7, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(32, 'ONE_BEDROOM', 2, 1, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(33, 'TWO_BEDROOM', 4, 3, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(34, 'ONE_BEDROOM', 2, 8, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(35, 'ONE_BEDROOM', 2, 3, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(36, 'TWO_BEDROOM', 4, 10, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(37, 'TWO_BEDROOM', 4, 10, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(38, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(39, 'TWO_BEDROOM', 4, 8, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(40, 'ONE_BEDROOM', 2, 5, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(41, 'ONE_BEDROOM', 2, 8, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(42, 'TWO_BEDROOM', 4, 7, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(43, 'ONE_BEDROOM', 2, 2, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(44, 'TWO_BEDROOM', 4, 8, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(45, 'TWO_BEDROOM', 4, 2, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(46, 'TWO_BEDROOM', 4, 8, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(47, 'TWO_BEDROOM', 4, 0, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(48, 'ONE_BEDROOM', 2, 10, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(49, 'ONE_BEDROOM', 2, 6, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(50, 'ONE_BEDROOM', 2, 9, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(51, 'TWO_BEDROOM', 4, 8, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(52, 'ONE_BEDROOM', 2, 4, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(53, 'ONE_BEDROOM', 2, 10, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(54, 'TWO_BEDROOM', 4, 3, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(55, 'ONE_BEDROOM', 2, 9, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(56, 'ONE_BEDROOM', 2, 5, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(57, 'ONE_BEDROOM', 2, 3, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(58, 'ONE_BEDROOM', 2, 7, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(59, 'ONE_BEDROOM', 2, 6, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(60, 'ONE_BEDROOM', 2, 5, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(61, 'ONE_BEDROOM', 2, 8, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(62, 'TWO_BEDROOM', 4, 7, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(63, 'ONE_BEDROOM', 2, 9, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(64, 'TWO_BEDROOM', 4, 7, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(65, 'TWO_BEDROOM', 4, 2, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(66, 'ONE_BEDROOM', 2, 10, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(67, 'ONE_BEDROOM', 2, 1, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(68, 'ONE_BEDROOM', 2, 6, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(69, 'TWO_BEDROOM', 4, 4, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(70, 'TWO_BEDROOM', 4, 6, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(71, 'ONE_BEDROOM', 2, 7, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(72, 'TWO_BEDROOM', 4, 4, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(73, 'TWO_BEDROOM', 4, 1, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(74, 'TWO_BEDROOM', 4, 9, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(75, 'ONE_BEDROOM', 2, 9, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(76, 'ONE_BEDROOM', 2, 2, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(77, 'ONE_BEDROOM', 2, 10, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(78, 'ONE_BEDROOM', 2, 5, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(79, 'ONE_BEDROOM', 2, 5, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(80, 'ONE_BEDROOM', 2, 0, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(81, 'ONE_BEDROOM', 2, 6, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(82, 'TWO_BEDROOM', 4, 8, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(83, 'ONE_BEDROOM', 2, 6, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(84, 'TWO_BEDROOM', 4, 6, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(85, 'ONE_BEDROOM', 2, 7, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(86, 'ONE_BEDROOM', 2, 3, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(87, 'ONE_BEDROOM', 2, 7, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(88, 'ONE_BEDROOM', 2, 4, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(89, 'ONE_BEDROOM', 2, 7, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(90, 'ONE_BEDROOM', 2, 0, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(91, 'ONE_BEDROOM', 2, 10, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(92, 'TWO_BEDROOM', 4, 3, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(93, 'ONE_BEDROOM', 2, 8, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(94, 'ONE_BEDROOM', 2, 0, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(95, 'TWO_BEDROOM', 4, 3, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(96, 'TWO_BEDROOM', 4, 7, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(97, 'TWO_BEDROOM', 4, 2, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(98, 'TWO_BEDROOM', 4, 4, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(99, 'ONE_BEDROOM', 2, 3, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(100, 'TWO_BEDROOM', 4, 5, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(101, 'ONE_BEDROOM', 2, 3, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(102, 'ONE_BEDROOM', 2, 2, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(103, 'ONE_BEDROOM', 2, 6, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(104, 'TWO_BEDROOM', 4, 2, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(105, 'ONE_BEDROOM', 2, 4, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(106, 'ONE_BEDROOM', 2, 1, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(107, 'TWO_BEDROOM', 4, 4, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(108, 'ONE_BEDROOM', 2, 2, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(109, 'TWO_BEDROOM', 4, 9, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(110, 'TWO_BEDROOM', 4, 5, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(111, 'ONE_BEDROOM', 2, 8, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(112, 'TWO_BEDROOM', 4, 4, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(113, 'TWO_BEDROOM', 4, 3, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(114, 'ONE_BEDROOM', 2, 1, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(115, 'ONE_BEDROOM', 2, 4, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(116, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(117, 'ONE_BEDROOM', 2, 6, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(118, 'TWO_BEDROOM', 4, 3, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(119, 'TWO_BEDROOM', 4, 5, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(120, 'TWO_BEDROOM', 4, 6, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(121, 'TWO_BEDROOM', 4, 9, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(122, 'TWO_BEDROOM', 4, 2, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(123, 'ONE_BEDROOM', 2, 8, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(124, 'ONE_BEDROOM', 2, 6, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(125, 'TWO_BEDROOM', 4, 3, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(126, 'TWO_BEDROOM', 4, 7, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(127, 'ONE_BEDROOM', 2, 9, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(128, 'ONE_BEDROOM', 2, 8, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(129, 'TWO_BEDROOM', 4, 9, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(130, 'ONE_BEDROOM', 2, 2, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(131, 'ONE_BEDROOM', 2, 6, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(132, 'ONE_BEDROOM', 2, 2, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(133, 'TWO_BEDROOM', 4, 4, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(134, 'ONE_BEDROOM', 2, 7, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(135, 'ONE_BEDROOM', 2, 4, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(136, 'TWO_BEDROOM', 4, 9, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(137, 'TWO_BEDROOM', 4, 9, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(138, 'TWO_BEDROOM', 4, 2, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(139, 'TWO_BEDROOM', 4, 7, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(140, 'ONE_BEDROOM', 2, 4, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(141, 'ONE_BEDROOM', 2, 7, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(142, 'TWO_BEDROOM', 4, 6, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(143, 'ONE_BEDROOM', 2, 3, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(144, 'TWO_BEDROOM', 4, 9, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(145, 'TWO_BEDROOM', 4, 3, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(146, 'TWO_BEDROOM', 4, 7, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(147, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(148, 'ONE_BEDROOM', 2, 9, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(149, 'ONE_BEDROOM', 2, 5, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(150, 'ONE_BEDROOM', 2, 8, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(151, 'TWO_BEDROOM', 4, 7, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(152, 'ONE_BEDROOM', 2, 3, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(153, 'ONE_BEDROOM', 2, 9, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(154, 'TWO_BEDROOM', 4, 2, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(155, 'ONE_BEDROOM', 2, 8, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(156, 'ONE_BEDROOM', 2, 4, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(157, 'ONE_BEDROOM', 2, 2, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(158, 'ONE_BEDROOM', 2, 6, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(159, 'ONE_BEDROOM', 2, 5, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(160, 'ONE_BEDROOM', 2, 4, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(161, 'ONE_BEDROOM', 2, 7, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(162, 'TWO_BEDROOM', 4, 6, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(163, 'ONE_BEDROOM', 2, 8, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(164, 'TWO_BEDROOM', 4, 6, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(165, 'TWO_BEDROOM', 4, 1, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(166, 'ONE_BEDROOM', 2, 9, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(167, 'ONE_BEDROOM', 2, 2, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(168, 'ONE_BEDROOM', 2, 5, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(169, 'TWO_BEDROOM', 4, 3, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(170, 'TWO_BEDROOM', 4, 5, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(171, 'ONE_BEDROOM', 2, 6, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(172, 'TWO_BEDROOM', 4, 3, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(173, 'TWO_BEDROOM', 4, 2, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(174, 'TWO_BEDROOM', 4, 8, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(175, 'ONE_BEDROOM', 2, 8, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(176, 'ONE_BEDROOM', 2, 1, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(177, 'ONE_BEDROOM', 2, 9, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(178, 'ONE_BEDROOM', 2, 4, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(179, 'ONE_BEDROOM', 2, 4, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(180, 'ONE_BEDROOM', 2, 1, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(181, 'ONE_BEDROOM', 2, 5, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(182, 'TWO_BEDROOM', 4, 7, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(183, 'ONE_BEDROOM', 2, 5, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(184, 'TWO_BEDROOM', 4, 5, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(185, 'ONE_BEDROOM', 2, 6, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(186, 'ONE_BEDROOM', 2, 2, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(187, 'ONE_BEDROOM', 2, 6, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(188, 'ONE_BEDROOM', 2, 3, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(189, 'ONE_BEDROOM', 2, 6, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(190, 'ONE_BEDROOM', 2, 1, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(191, 'ONE_BEDROOM', 2, 9, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(192, 'TWO_BEDROOM', 4, 2, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(193, 'ONE_BEDROOM', 2, 7, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(194, 'ONE_BEDROOM', 2, 1, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(195, 'TWO_BEDROOM', 4, 2, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(196, 'TWO_BEDROOM', 4, 6, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(197, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(198, 'TWO_BEDROOM', 4, 3, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(199, 'ONE_BEDROOM', 2, 2, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(200, 'TWO_BEDROOM', 4, 4, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(201, 'ONE_BEDROOM', 2, 2, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(202, 'ONE_BEDROOM', 2, 1, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(203, 'ONE_BEDROOM', 2, 3, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(204, 'TWO_BEDROOM', 4, 3, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(205, 'ONE_BEDROOM', 2, 2, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(206, 'ONE_BEDROOM', 2, 2, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(207, 'TWO_BEDROOM', 4, 5, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(208, 'ONE_BEDROOM', 2, 4, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(209, 'TWO_BEDROOM', 4, 2, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(210, 'TWO_BEDROOM', 4, 1, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(211, 'ONE_BEDROOM', 2, 5, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(212, 'TWO_BEDROOM', 4, 2, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(213, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(214, 'ONE_BEDROOM', 2, 3, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(215, 'ONE_BEDROOM', 2, 2, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(216, 'TWO_BEDROOM', 4, 3, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(217, 'ONE_BEDROOM', 2, 4, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(218, 'TWO_BEDROOM', 4, 1, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(219, 'TWO_BEDROOM', 4, 2, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(220, 'TWO_BEDROOM', 4, 3, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(221, 'TWO_BEDROOM', 4, 4, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(222, 'TWO_BEDROOM', 4, 1, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(223, 'ONE_BEDROOM', 2, 5, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(224, 'ONE_BEDROOM', 2, 3, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(225, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(226, 'TWO_BEDROOM', 4, 4, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(227, 'ONE_BEDROOM', 2, 2, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(228, 'ONE_BEDROOM', 2, 4, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(229, 'TWO_BEDROOM', 4, 5, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(230, 'ONE_BEDROOM', 2, 1, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(231, 'ONE_BEDROOM', 2, 4, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(232, 'ONE_BEDROOM', 2, 1, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(233, 'TWO_BEDROOM', 4, 2, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(234, 'ONE_BEDROOM', 2, 3, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(235, 'ONE_BEDROOM', 2, 1, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(236, 'TWO_BEDROOM', 4, 3, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(237, 'TWO_BEDROOM', 4, 4, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(238, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(239, 'TWO_BEDROOM', 4, 3, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(240, 'ONE_BEDROOM', 2, 2, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(241, 'ONE_BEDROOM', 2, 4, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(242, 'TWO_BEDROOM', 4, 3, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(243, 'ONE_BEDROOM', 2, 1, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(244, 'TWO_BEDROOM', 4, 4, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(245, 'TWO_BEDROOM', 4, 1, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(246, 'TWO_BEDROOM', 4, 4, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(247, 'TWO_BEDROOM', 4, 0, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(248, 'ONE_BEDROOM', 2, 4, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(249, 'ONE_BEDROOM', 2, 3, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(250, 'ONE_BEDROOM', 2, 5, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(251, 'TWO_BEDROOM', 4, 4, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(252, 'ONE_BEDROOM', 2, 2, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(253, 'ONE_BEDROOM', 2, 5, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(254, 'TWO_BEDROOM', 4, 1, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(255, 'ONE_BEDROOM', 2, 5, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(256, 'ONE_BEDROOM', 2, 2, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(257, 'ONE_BEDROOM', 2, 1, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(258, 'ONE_BEDROOM', 2, 3, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(259, 'ONE_BEDROOM', 2, 2, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(260, 'ONE_BEDROOM', 2, 3, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(261, 'ONE_BEDROOM', 2, 4, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(262, 'TWO_BEDROOM', 4, 3, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(263, 'ONE_BEDROOM', 2, 4, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(264, 'TWO_BEDROOM', 4, 3, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(265, 'TWO_BEDROOM', 4, 1, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(266, 'ONE_BEDROOM', 2, 5, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(267, 'ONE_BEDROOM', 2, 1, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(268, 'ONE_BEDROOM', 2, 3, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(269, 'TWO_BEDROOM', 4, 2, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(270, 'TWO_BEDROOM', 4, 3, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(271, 'ONE_BEDROOM', 2, 3, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(272, 'TWO_BEDROOM', 4, 2, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(273, 'TWO_BEDROOM', 4, 1, 'Amplio apartamento de dos dormitorios con terraza y cocina moderna.'),
(274, 'TWO_BEDROOM', 4, 4, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(275, 'ONE_BEDROOM', 2, 4, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(276, 'ONE_BEDROOM', 2, 1, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(277, 'ONE_BEDROOM', 2, 5, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(278, 'ONE_BEDROOM', 2, 2, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(279, 'ONE_BEDROOM', 2, 2, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(280, 'ONE_BEDROOM', 2, 0, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(281, 'ONE_BEDROOM', 2, 3, 'Moderno apartamento de una habitación con cocina americana integrada.'),
(282, 'TWO_BEDROOM', 4, 4, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(283, 'ONE_BEDROOM', 2, 3, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(284, 'TWO_BEDROOM', 4, 3, 'Elegante unidad de dos habitaciones con salón luminoso y baño completo.'),
(285, 'ONE_BEDROOM', 2, 4, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(286, 'ONE_BEDROOM', 2, 1, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(287, 'ONE_BEDROOM', 2, 4, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(288, 'ONE_BEDROOM', 2, 2, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(289, 'ONE_BEDROOM', 2, 4, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(290, 'ONE_BEDROOM', 2, 0, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(291, 'ONE_BEDROOM', 2, 5, 'Compacto pero elegante apartamento de un dormitorio perfectamente equipado.'),
(292, 'TWO_BEDROOM', 4, 1, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(293, 'ONE_BEDROOM', 2, 4, 'Luminoso estudio de una habitación con vistas al jardín interior.'),
(294, 'ONE_BEDROOM', 2, 0, 'Acogedor apartamento de una habitación con diseño moderno y funcional.'),
(295, 'TWO_BEDROOM', 4, 1, 'Disfruta de un espacioso apartamento de dos habitaciones con vistas panorámicas.'),
(296, 'TWO_BEDROOM', 4, 3, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(297, 'TWO_BEDROOM', 4, 1, 'Cómodo apartamento de dos dormitorios ideal para familias.'),
(298, 'TWO_BEDROOM', 4, 2, 'Espacioso piso de dos habitaciones con acabados de alta calidad.'),
(299, 'ONE_BEDROOM', 2, 1, 'Práctico piso de un dormitorio en planta baja con acceso directo.'),
(300, 'TWO_BEDROOM', 4, 2, 'Espacioso piso de dos habitaciones con acabados de alta calidad.');